apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace: demo
spec:
  replicas: 2
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: PodAlert
metadata:
  name: pod-status-demo-0
  namespace: demo
spec:
  selector:
    matchLabels:
      app: nginx
  check: pod_status
  checkInterval: 30s
  alertInterval: 2m
  notifierSecretName: notifier-config
  receivers:
  - notifier: Mailgun
    state: CRITICAL
    to: ["ops@example.com"]
