package e2e

const (
	ICINGA_API_USER           = "icingaapi"
	ICINGA_API_PASSWORD       = "VDYBqn3wtc-MNdlX"
	ICINGA_WEB_ADMIN_PASSWORD = "DrxQsltR2OC162xl"
	ICINGA_CA_CERT            = `-----BEGIN CERTIFICATE-----
MIIBljCCATygAwIBAgIUVRBXtXplXRZeWF27MO3m/6RaYTMwCgYIKoZIzj0EAwIw
HzEdMBsGA1UEAxMUc2VhcmNobGlnaHQtb3BlcmF0b3IwHhcNMTcwNzEzMTAyOTAw
WhcNMjcwNzExMTAyOTAwWjAfMR0wGwYDVQQDExRzZWFyY2hsaWdodC1vcGVyYXRv
cjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEv6MQ39sRINiFCQ6D7Spl63VV9p
ifvcVpT6Fe67GvZ/3cl8ok+Y3mLXxiS1j/JkLzvdKNdyThSoaz3VtmA3Tc2jVjBU
MA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgECMB0GA1UdDgQWBBR/
iG0pBLcyXdAq/fBSfkxQwaEm8zAPBgNVHREECDAGhwR/AAABMAoGCCqGSM49BAMC
A0gAMEUCIQCwS6Cs1jDLLdJKqAGIhVxHXAq4D1YrDh31jhFwqLYYoQIgLyWPEhv9
tRLWuLZaKVrFtq4s6JUadeHNiwjROd7P8BU=
-----END CERTIFICATE-----`
)
