// Code generated by "stringer -type=IcingaState ../../pkg/icinga/types.go"; DO NOT EDIT.

package icinga

import "fmt"

const _IcingaState_name = "OkWarningCriticalUnknown"

var _IcingaState_index = [...]uint8{0, 2, 9, 17, 24}

func (i State) String() string {
	if i < 0 || i >= State(len(_IcingaState_index)-1) {
		return fmt.Sprintf("IcingaState(%d)", i)
	}
	return _IcingaState_name[_IcingaState_index[i]:_IcingaState_index[i+1]]
}
