// Code generated by "stringer -type=State ../../pkg/icinga/types.go"; DO NOT EDIT.

package icinga

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[Warning-1]
	_ = x[Critical-2]
	_ = x[Unknown-3]
}

const _State_name = "OKWarningCriticalUnknown"

var _State_index = [...]uint8{0, 2, 9, 17, 24}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
